name: example-chrome
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

env:
  DEBUG: cypress:server:browsers:chrome

jobs:

  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Chrome stable
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: stable

      - name: Chrome headless
        if: always()
        uses: ./
        with:
          # Print information about the system and current environment
          # including detected browsers
          # which are pre-installed in GitHub-hosted runners
          # see https://on.cypress.io/command-line#cypress-info
          # For convenience, (mis-)use build parameter to get cypress info
          build: npx cypress info
          working-directory: examples/browser
          browser: chrome
          # As of Cypress v8.0 the `cypress run` command
          # executes tests in `headless` mode by default

      - name: Chrome headless debug
        if: always()
        uses: ./
        with:
          build: npx cypress info
          working-directory: examples/browser
          browser: chrome
        env:
          DEBUG: 'cypress:*'

      - name: Chrome headed
        if: always()
        uses: ./
        with:
          # Cypress and dependencies are already installed
          install: false
          working-directory: examples/browser
          browser: chrome
          headed: true
