name: example-ci-test
on:
  workflow_dispatch:

jobs:
  ci-standalone:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci
        working-directory: examples/basic

  action-ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: ./
        with:
          working-directory: examples/basic
