name: example-debug
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:
  debug-logs:
    runs-on: ubuntu-22.04
    container: cypress/browsers:node18.12.0-chrome106-ff106
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress debug logs 📝
        uses: ./
        env:
          DEBUG: '@cypress/github-action'
        with:
          working-directory: examples/basic
