name: example-mochawesome
on:
  workflow_dispatch:
jobs:
  basic-mochawesome:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress tests
        uses: cypress-io/github-action@v6
        with:
          working-directory: examples/mochawesome
      - name: Upload mochawesome report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: examples/mochawesome/cypress/reports
