name: example-chromium
on:
  push:
    branches:
      - 'master'
  pull_request:
  workflow_dispatch:

jobs:

  tests:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Chromium headless
        uses: ./
        with:
          # Print information about the system and current environment
          # including detected browsers
          # which are pre-installed in GitHub-hosted runners
          # see https://on.cypress.io/command-line#cypress-info
          # We do not need the build parameter to build an app here
          # because the remote https://example.cypress.io site
          # is already built and running, and so for convenience
          # we repurpose the build parameter to get cypress info instead.
          build: npx cypress info
          working-directory: examples/browser
          browser: chromium
          # As of Cypress v8.0 the `cypress run` command
          # executes tests in `headless` mode by default

      - name: Chromium headed
        uses: ./
        with:
          # Cypress and dependencies are already installed
          install: false
          working-directory: examples/browser
          browser: chromium
          headed: true
